version: '3.8'

services:
  anndata2rdf:
    image: anndata2rdf:latest
    container_name: anndata_to_rdf
    volumes:
      - ./src/config:/app/src/config
      - ./src/curated_data:/app/src/curated_data
      - ./src/dataset:/app/src/dataset
      - ./src/graph:/app/src/graph
