site_name: Cell Type Knowledge Graph Documentation
nav:
  - Home: index.md
  - Access Guide: access_guide.md
  - Query Guide: query_guide.md
  - Content Analysis: queries_for_content_analysis.md
  - Dataset Curation Guidelines: dataset_curation_guidelines.md
  - Schema: schema.md
  - Reports:
      - Global totals: reports/sections/01-global-totals.md
      - Counts by key label: reports/sections/02-counts-by-key-label.md
      - Average degree by label: reports/sections/03-average-degree-by-label.md
      - Relationship types by count: reports/sections/04-relationship-types-by-count.md
      - Top tissues across clusters: reports/sections/05-top-tissues-across-clusters.md
      - Top diseases across clusters: reports/sections/06-top-diseases-across-clusters.md
      - Assay types across clusters: reports/sections/07-assay-types-across-clusters.md
      - Development stages across clusters: reports/sections/08-development-stages-across-clusters.md
      - How many datasets and clusters with sources?: reports/sections/09-how-many-datasets-and-clusters-with-sources.md
      - Top datasets by clusters: reports/sections/10-top-datasets-by-clusters.md
      - List all dataset titles alphabetically with row numbers: reports/sections/11-list-all-dataset-titles-alphabetically-with-row-numbers.md

theme: readthedocs
docs_dir: docs

markdown_extensions:
  - tables
  - md_in_html
