site_name: Cell Type Knowledge Graph Documentation
nav:
  - Home: index.md
  - Access Guide: access_guide.md
  - Query Guide: query_guide.md
  - Dataset Curation Guidelines: dataset_curation_guidelines.md
theme: readthedocs
docs_dir: docs
