version: '3.8'

services:
  anndata2rdf:
    image: ghcr.io/cellular-semantics/cl_kg/anndata2rdf:latest
    # container_name: anndata_to_rdf
    volumes:
      - ../anndata2rdf/src/config:/app/src/config
      - ../anndata2rdf/src/curated_data:/app/src/curated_data
      - ../anndata2rdf/src/dataset:/app/src/dataset
      - ./config/collectdata/local_ontologies:/app/src/graph/
    command: /bin/sh -c "python src/process.py"

  triplestore:
    image: eclipse/rdf4j-workbench:3.7.7
    # container_name: triplestore
    environment:
      - JAVA_OPTS=-Xms1G -Xmx5G
    ports:
      - 8081:8080
    volumes:
      - triplestore_data:/var/rdf4j

  obask-kb:
    image: ghcr.io/obasktools/obask-kb:latest
    # container_name: obask-kb
    environment:
      - NEO4J_AUTH=neo4j/neo
      - NEO4J_dbms_read__only=false
      - NEO4J_dbms_databases_default__to__read__only=false
      - NEO4J_dbms_memory_heap_maxSize=4G
      - NEO4J_dbms_memory_heap_initial__size=1G
    ports:
      - 7475:7474
      - 7688:7687
    links:
      - solr
    depends_on:
      obask-dumps:
        condition: service_completed_successfully
    volumes:
      - obask_data:/input
      - obask_neo4j_data:/data # for Neo4j DB itself
    healthcheck:
      test: [ "CMD", "wget", "-O", "-", "http://obask-kb:7474" ]
      interval: 18s
      timeout: 12s
      retries: 20
      start_period: 3s

  obask-collectdata:
    image: ghcr.io/obasktools/pipeline-collectdata:latest
    # container_name: collectdata
    depends_on:
      triplestore:
        condition: service_started
      anndata2rdf:
        condition: service_completed_successfully
    volumes:
      - ./config/collectdata:/opt/conf_base/config/collectdata
      - obask_data:/out

  obask-updatetriplestore:
    image: ghcr.io/obasktools/pipeline-updatetriplestore:latest
    # container_name: updatetriplestore
    depends_on:
      obask-collectdata:
        condition: service_completed_successfully
    links:
      - triplestore
    environment:
      - SERVER=http://triplestore:8080
    volumes:
      - ./config/updatetriplestore:/opt/conf_base/config/updatetriplestore
      - obask_data:/data

  obask-dumps:
    image: ghcr.io/obasktools/pipeline-dumps:latest
    # container_name: dumps
    depends_on:
      pipeline-mapper:
        condition: service_completed_successfully
    links:
      - triplestore
    volumes:
      - ./config/dumps:/opt/conf_base/config/dumps
      - obask_data:/out

  obask-updateprod:
    image: ghcr.io/obasktools/pipeline-updateprod:latest
    # container_name: updateprod
    depends_on:
      obask-kb:
        condition: service_healthy
    links:
      - obask-kb
    environment:
      - password=neo4j/neo
      - server=http://obask-kb:7474
    volumes:
      - ./config/update-prod:/opt/conf_base/config/update-prod
      - obask_data:/input

  solr:
    image: solr:8.11
    # container_name: solr
    ports:
      - 8994:8983
    depends_on:
      - obask-dumps
    links:
      - obask-dumps
    volumes:
      - solr_data:/var/solr
    entrypoint:
      - bash
      - "-c"
      - "precreate-core ontology; precreate-core bdsdump; exec solr -f"

  obask-updatesolr:
    image: ghcr.io/obasktools/pipeline-updatesolr:latest
    # container_name: updatesolr
    links:
      - solr
    volumes:
      - obask_data:/data
    depends_on:
      obask-dumps:
        condition: service_completed_successfully

  obask-ontology-search:
    image: ghcr.io/obasktools/ontology-search:latest
    # container_name: ontology-search
    ports:
      - 8008:8007
    environment:
      - PYTHON_ENV=production
      - OBASK_URL_PREFIX=/cl-kg
    depends_on:
      - solr
      - obask-updatesolr
    links:
      - solr

  pipeline-mapper:
    image: ghcr.io/cellular-semantics/cl_kg/translator_api_mapper:latest
    # container_name: pipeline_mapper
    depends_on:
      obask-updatetriplestore:
        condition: service_completed_successfully
    environment:
      - ENDPOINT_URL=http://triplestore:8080/rdf4j-server/repositories/obask
    links:
      - triplestore

  obask-make-kb-readonly:
    image: docker:cli
    depends_on:
      obask-updateprod:
        condition: service_completed_successfully
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: >
      sh -c 'echo "[INFO] Restarting obask-kb in read-only mode..." && \
        docker stop cl_kb_pipeline-obask-kb-1 && \
        docker rm cl_kb_pipeline-obask-kb-1 && \
        docker run -d --name cl_kb_pipeline-obask-kb-1 \
          -p 7475:7474 -p 7688:7687 \
          -v cl_kb_pipeline_obask_data:/input \
          -v cl_kb_pipeline_obask_neo4j_data:/data \
          -e NEO4J_AUTH=neo4j/neo \
          -e NEO4J_dbms_read__only=true \
          -e NEO4J_dbms_databases_default__to__read__only=true \
          -e NEO4J_dbms_memory_heap_maxSize=4G \
          -e NEO4J_dbms_memory_heap_initial__size=1G \
          ghcr.io/obasktools/obask-kb:latest'

volumes:
  obask_data:
  solr_data:
  triplestore_data:
  obask_neo4j_data:
