version: '3.8'

services:
  anndata2rdf:
    image: ghcr.io/cellular-semantics/cl_kg:main
    container_name: anndata_to_rdf
    volumes:
      - ./src/config:/app/src/config
      - ./src/curated_data:/app/src/curated_data
      - ./src/dataset:/app/src/dataset
      - obask_graph_data:/app/src/graph
      - clkg_bitmap_data:/app/src/bitmaps
volumes:
  obask_graph_data:
  clkg_bitmap_data:
