version: '3.8'

services:
  anndata2rdf:
    image: ghcr.io/cellular-semantics/cl_kg:main@sha256:3bfcbd32a8d6825b02457d55be30fcc4debdcfaf919f57f482b8af4c033ed6d6
    container_name: anndata_to_rdf
    volumes:
      - ./src/config:/app/src/config
      - ./src/curated_data:/app/src/curated_data
      - ./src/dataset:/app/src/dataset
      - obask_data:/app/src/graph
volumes:
  obask_data:
