name: Publish mkdocs documentation

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      
permissions:
  contents: write
  
jobs:
  build-and-publish:
    name: Publish mkdocs documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
      - name: Show mkdocs.yml (for sanity)
        run: |
          echo "----- mkdocs.yml -----"
          sed -n '1,200p' mkdocs.yml
          echo "----------------------"
      - name: Install MkDocs
        run: pip install mkdocs
      - name: Build (strict) to catch config/nav issues
        run: mkdocs build --verbose
      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: mkdocs.yml
